// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpecificationPattern.Demo.Infrastructure;

namespace SpecificationPattern.Demo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190322130548_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.Character", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Character");
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.CharacterEpisode", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("EpisodeId");

                    b.HasKey("CharacterId", "EpisodeId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("CharactersEpisodes");
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.CharacterFriend", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("FriendId");

                    b.HasKey("CharacterId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("CharacterFriends");
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.Episode", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("HeroId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.Planet", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Climate");

                    b.Property<string>("Name");

                    b.Property<string>("Population");

                    b.Property<string>("Terrain");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.Droid", b =>
                {
                    b.HasBaseType("SpecificationPattern.Demo.CrossCutting.Entities.Character");

                    b.Property<string>("PrimaryFunction");

                    b.HasDiscriminator().HasValue("Droid");
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.Human", b =>
                {
                    b.HasBaseType("SpecificationPattern.Demo.CrossCutting.Entities.Character");

                    b.Property<int?>("HomePlanetId");

                    b.HasIndex("HomePlanetId");

                    b.HasDiscriminator().HasValue("Human");
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.CharacterEpisode", b =>
                {
                    b.HasOne("SpecificationPattern.Demo.CrossCutting.Entities.Character", "Character")
                        .WithMany("CharacterEpisodes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SpecificationPattern.Demo.CrossCutting.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.CharacterFriend", b =>
                {
                    b.HasOne("SpecificationPattern.Demo.CrossCutting.Entities.Character", "Character")
                        .WithMany("CharacterFriends")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SpecificationPattern.Demo.CrossCutting.Entities.Character", "Friend")
                        .WithMany("FriendCharacters")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.Episode", b =>
                {
                    b.HasOne("SpecificationPattern.Demo.CrossCutting.Entities.Character", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId");
                });

            modelBuilder.Entity("SpecificationPattern.Demo.CrossCutting.Entities.Human", b =>
                {
                    b.HasOne("SpecificationPattern.Demo.CrossCutting.Entities.Planet", "HomePlanet")
                        .WithMany("Humans")
                        .HasForeignKey("HomePlanetId");
                });
#pragma warning restore 612, 618
        }
    }
}
